package com.cameleonnbss.s20tuner.core

import android.content.Context

/**
 * Auto engine: OFF = apply preset once; AUTO = root daemon switching between
 * four pre-generated preset scripts based on load / battery temp / screen.
 * The daemon only re-applies on state CHANGE (scripts are idempotent anyway).
 */
object AutoEngine {

    private const val SVC = "/data/adb/service.d/990oc_boot.sh"
    private const val PIDF = "/data/local/tmp/990oc_auto.pid"
    private const val LOG = "/data/local/tmp/990oc_auto.log"
    private const val BASE = "/data/adb/990oc"

    fun running(): Boolean {
        val r = Shell.exec(
            "if [ -f $PIDF ] && [ -d /proc/\$(cat $PIDF) ]; then echo RUNNING; else echo STOPPED; fi", 8000
        )
        return r.out.trim() == "RUNNING"
    }

    fun bootRestoreEnabled(): Boolean {
        val r = Shell.exec("[ -f $SVC ] && echo YES || echo NO", 6000)
        return r.out.trim() == "YES"
    }

    fun setBootRestore(on: Boolean, json: String): String {
        val b64 = android.util.Base64.encodeToString(json.toByteArray(), android.util.Base64.NO_WRAP)
        val sb = StringBuilder()
        sb.append("mkdir -p /data/adb/service.d $BASE\n")
        if (on) {
            sb.append("echo '$b64' | base64 -d > $BASE/boot.json\n")
            // boot service: regenerate the apply script from the saved config and run it
            val wrapper = "#!/system/bin/sh\n" +
                    "(while [ \"\$(getprop sys.boot_completed)\" != \"1\" ]; do sleep 2; done\n" +
                    "sleep 12\n" +
                    "if [ -f $BASE/boot.json ]; then\n" +
                    "  sh $BASE/boot_apply.sh >/dev/null 2>&1\n" +
                    "fi) &\n"
            // boot_apply.sh is regenerated by the app whenever config changes (see setBootRestore caller)
            sb.append("printf '%s\\n' ")
            sb.append(wrapper.lines().joinToString(" ") { "'$it'" })
            sb.append(" > $SVC\n")
            sb.append("chmod 755 $SVC\n")
        } else {
            sb.append("rm -f $SVC\n")
        }
        val r = Shell.exec(sb.toString())
        return if (r.ok) (if (on) "Boot restore enabled" else "Boot restore disabled") else "Failed: ${r.err}"
    }

    /** Writes the boot apply script from a config (call whenever config changes while boot restore is on). */
    fun syncBootApply(tables: Map<String, List<Int>>, gpuTable: List<Int>, json: String): String {
        val cfg = try { OcConfig.fromJson(json) } catch (_: Exception) { return "bad config" }
        val script = ApplyEngine.buildScript(cfg, tables, gpuTable)
        val b64 = android.util.Base64.encodeToString(script.toByteArray(), android.util.Base64.NO_WRAP)
        val r = Shell.exec(
            "mkdir -p $BASE\n echo '$b64' | base64 -d > $BASE/boot_apply.sh\n chmod 755 $BASE/boot_apply.sh\n echo OK", 10000
        )
        return if (r.out.contains("OK")) "boot apply synced" else "sync failed"
    }

    /** Starts/stops the auto daemon; pre-generates the four preset scripts. */
    fun setAuto(ctx: Context, on: Boolean, tables: Map<String, List<Int>>, gpuTable: List<Int>): String {
        val sb = StringBuilder()
        sb.append("mkdir -p $BASE\n")
        if (on) {
            val presets = linkedMapOf(
                "stock" to OcPresets.stock,
                "oc" to OcPresets.gaming,
                "uc" to OcPresets.battery,
                "sleep" to OcPresets.sleep
            )
            for ((name, cfg) in presets) {
                val script = ApplyEngine.buildScript(cfg, tables, gpuTable)
                val b64 = android.util.Base64.encodeToString(script.toByteArray(), android.util.Base64.NO_WRAP)
                sb.append("echo '$b64' | base64 -d > $BASE/$name.sh\n")
            }
            val daemon = daemonScript()
            val b64 = android.util.Base64.encodeToString(daemon.toByteArray(), android.util.Base64.NO_WRAP)
            sb.append("echo '$b64' | base64 -d > $BASE/auto.sh\n")
            sb.append("[ -f $PIDF ] && kill \$(cat $PIDF) 2>/dev/null; rm -f $PIDF\n")
            sb.append("(nohup /system/bin/sh $BASE/auto.sh >/dev/null 2>&1 &)\n")
            sb.append("sleep 1\n")
            sb.append("if [ -f $PIDF ] && [ -d /proc/\$(cat $PIDF) ]; then echo STARTED; else echo FAILED; fi\n")
        } else {
            sb.append("[ -f $PIDF ] && kill \$(cat $PIDF) 2>/dev/null; rm -f $PIDF\n")
            sb.append("echo OFF\n")
        }
        val r = Shell.exec(sb.toString(), 20000)
        return when {
            on && r.out.contains("STARTED") -> "Auto mode started"
            on -> "Failed to start: ${r.err.takeLast(80)}"
            else -> "Auto mode off"
        }
    }

    fun tailLog(): String {
        val r = Shell.exec("tail -25 $LOG 2>/dev/null", 8000)
        return r.out.ifBlank { "(no log yet)" }
    }

    private fun daemonScript(): String {
        val s = StringBuilder()
        s.append("#!/system/bin/sh\n")
        s.append("# Exynos 990 auto OC/UC daemon\n")
        s.append("echo $$ > $PIDF\n")
        s.append("echo \"\$(date '+%H:%M:%S') 990oc auto started\" >> $LOG\n")
        s.append("last=init\n")
        s.append("while :; do\n")
        s.append("  awake=\$(dumpsys power 2>/dev/null | grep -c 'mWakefulness=Awake')\n")
        s.append("  load=\$(cut -d' ' -f1 /proc/loadavg 2>/dev/null | awk '{printf \"%d\", \$1*100}')\n")
        s.append("  temp=\$(cat ${Sysfs.BAT_TEMP} 2>/dev/null)\n")
        s.append("  [ -z \"\$load\" ] && load=0\n")
        s.append("  [ -z \"\$temp\" ] && temp=0\n")
        s.append("  if [ \"\$awake\" -eq 0 ]; then new=sleep\n")
        s.append("  elif [ \"\$temp\" -ge 400 ]; then new=uc\n")
        s.append("  elif [ \"\$load\" -ge 250 ]; then new=oc\n")
        s.append("  else new=stock; fi\n")
        s.append("  if [ \"\$new\" != \"\$last\" ]; then\n")
        s.append("    sh $BASE/\$new.sh >/dev/null 2>&1\n")
        s.append("    echo \"\$(date '+%H:%M:%S') \$new load=\$load temp=\$temp\" >> $LOG\n")
        s.append("    last=\$new\n")
        s.append("  fi\n")
        s.append("  echo \$new > ${Sysfs.STATE_PATH} 2>/dev/null\n")
        s.append("  sleep 4\n")
        s.append("done\n")
        return s.toString()
    }
}
